using System.Collections.Generic;
using UnityEngine;

namespace _Darkland.Sources.Models {

    public static class CharacterNames {

        public static string RandomName() => Names[Random.Range(0, Names.Count - 1)];
        
        public static List<string> Names = new List<string> {
            "Ptorik",
            "Joz",
            "Varog",
            "Gethrod",
            "Hezra",
            "Feron",
            "Ophni",
            "Colborn",
            "Fintis",
            "Gatlin",
            "Jinto",
            "Hagalbar",
            "Krinn",
            "Lenox",
            "Revvyn",
            "Hodus",
            "Dimian",
            "Paskel",
            "Kontas",
            "Weston",
            "Azamarr",
            "Jather",
            "Tekren",
            "Jareth",
            "Adon",
            "Zaden",
            "Eune",
            "Graff",
            "Tez",
            "Jessop",
            "Gunnar",
            "Pike",
            "Domnhar",
            "Baske",
            "Jerrick",
            "Mavrek",
            "Riordan",
            "Wulfe",
            "Straus",
            "Tyvrik",
            "Henndar",
            "Favroe",
            "Whit",
            "Jaris",
            "Renham",
            "Kagran",
            "Lassrin",
            "Vadim",
            "Arlo",
            "Quintis",
            "Vale",
            "Caelan",
            "Yorjan",
            "Khron",
            "Ishmael",
            "Jakrin",
            "Fangar",
            "Roux",
            "Baxar",
            "Hawke",
            "Gatlen",
            "Barak",
            "Nazim",
            "Kadric",
            "Paquin",
            "Kent",
            "Moki",
            "Rankar",
            "Lothe",
            "Ryven",
            "Clawsen",
            "Pakker",
            "Embre",
            "Cassian",
            "Verssek",
            "Dagfinn",
            "Ebraheim",
            "Nesso",
            "Eldermar",
            "Rivik",
            "Rourke",
            "Barton",
            "Hemm",
            "Sarkin",
            "Blaiz",
            "Talon",
            "Agro",
            "Zagaroth",
            "Turrek",
            "Esdel",
        };
    }

}